# Generated by Django 5.1.4 on 2024-12-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("waste", "0002_alter_category_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="waste.municipality",
            ),
        ),
    ]
