services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6432:5432"

  web:
    build:
      context: .
      target: web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    environment:
      - DEBUG=True
      - DATABASE_URL=psql://postgres:postgres@db/postgres
    env_file:
      - .env
    depends_on:
      - db
    command: "/app/entrypoint.sh dev"

  api:
    build:
      context: .
      target: web
    command: "poetry run fastapi run ./API/main.py --port 6969"
    ports:
      - "6969:6969"
    env_file:
      - api.env

    
  llm-document-api:
    build:
      context: .
      target: llm-document-api
    ports:
      - "8001:8000"
    env_file:
      - api.env


volumes:
  postgres_data:
