services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      target: web
    ports:
      - "8001:8000"
    volumes:
      - ./:/app/
    environment:
      - DEBUG=True
      - DATABASE_URL=psql://postgres:postgres@db/postgres
    env_file:
      - .env
    depends_on:
      - db
    command: "/app/entrypoint.sh dev"

volumes:
  postgres_data:
