services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6432:5432"

  web:
    build:
      context: .
      target: web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    environment:
      - DEBUG=True
      - DATABASE_URL=psql://postgres:postgres@db/postgres
    env_file:
      - .env
    depends_on:
      - db
    command: "/app/entrypoint.sh dev"

  api:
    build:
      context: .
      target: web
    command: "poetry run fastapi run ./API/main.py --port 6969"
    ports:
      - "6969:6969"
    environment:
      - NEO4J_URI=bolt://neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=bitnami1
    env_file:
      - api.env
    depends_on:
      - neo4j

  llm-document-api:
    build:
      context: .
      target: llm-document-api
    ports:
      - "8001:8000"
    environment:
      - NEO4J_URI=bolt://neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=bitnami1
    env_file:
      - api.env
    depends_on:
      - neo4j
  neo4j:
    image: bitnami/neo4j
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  postgres_data:
  neo4j_data:
