# Generated by Django 5.1.4 on 2024-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0002_alter_category_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="targets",
            field=models.ManyToManyField(blank=True, to="waste.target"),
        ),
    ]
