# Generated by Django 5.1.4 on 2024-12-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_document_options_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='dont',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.municipality'),
        ),
    ]
