# Generated by Django 5.1.4 on 2024-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_category_do_category_dont_category_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='show_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
