# Generated by Django 5.1.4 on 2025-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0006_location_show_on_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("material", models.CharField(blank=True, max_length=255)),
                ("material_number", models.IntegerField(default=0)),
                ("material_type", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["material_number", "product_name"],
            },
        ),
    ]
